### ISSUE TITLE
`99-okd-worker-disable-mitigations` disables intel pstate on bare metal

### ISSUE THREAD

**Issue by Gentoli** [openshift/okd-machine-os#332]
[99-okd-worker-disable-mitigations.yaml](https://github.com/openshift/okd-machine-os/blob/5686ca6a95b95437e70c79d9c72cbcdadd736f3e/manifests/99-okd-worker-disable-mitigations.yaml) is added to fix an issue on AWS m6 virtualized instances (according to commit message), this should not be applied on other machine types such as bare metal. 

`intel_pstate` will be better managed by Node Tuning Operator.

Is there a work around to remove this on the existing OKD cluster? Deleting the machine config results it being recreated by the ClusterVersion.

Can there be a better way to machine specific patches?

**Comment by Gentoli** [comment]
@vrutkovs

**Comment by LorbusChris** [comment]
Manually removing (or editing) the `99-okd-worker-disable-mitigations` MachineConfig object should result in a new rendered-machine-config being created and applied. Is this what you tried already?

**Comment by Gentoli** [comment]
@LorbusChris Yes, I tried deleting it. It does create a new rendered machine config and the node reboots, but then the `99-okd-worker-disable-mitigations` is added back and node reboots again.

**Comment by LorbusChris** [comment]
/remove-lifecycle stale
@vrutkovs I think we should consider removing that karg, and either selectively enable it, or indeed leave it to the node tuning operator. WDYT?
