### ISSUE TITLE
Is there more detail build process guide ?

### ISSUE THREAD

**Issue by wanglmb** [openshift/okd-machine-os#341]
Is there any descrition more detail about the build process ？The Build process in README.md is too little to follow.
e.g: 
https://coreos.github.io/coreos-assembler/building-fcos/

**Comment by fortinj66** [comment]
There are a few things you need to do if you are building "locally." It is a three step process

1.  `podman build -f Dockerfile.ci -t <through away tag> . `
  
     This does the bulk of the build.  Because the build process uses `cosa` it is looking for KVM to be available.  In order to insure this, the build actually happens on a remote server in Cirrus CI.  If you do happen to have KVM available you could hack Dockerfile.cosa and run it locally.
     
     When the build completes there will be a log and towards the bottom there will be a line `Committing container.` The next line will have the initial container image needed for step 2.
     
2.  Copy Dockerfile.template to Dockerfile and edit the FROM line and replace `INITIAL_IMAGE`  with the image from step 1.

3. podman build -f Dockerfile -t <whatever tag you want> .
   
    This will complete the build process and leave you with an image you can add to a new release.

**Comment by wanglmb** [comment]
thanks for the explaination.
I am trying the steps without any change to github. but met the following errors at step2#:
Am I missing something else ?
----------------------
[root@kubernetes okd-machine-os]#  podman build -f Dockerfile.ci -t okd-mos .
STEP 1/4: FROM quay.io/vrutkovs/cirrus-run
STEP 2/4: WORKDIR /go/src/github.com/openshift/okd-machine-os
--> Using cache ecf7aa567afaa38b0bd09c96e8098cc33df085559bb8bd4e8f1fd425c950016f
--> ecf7aa567af
STEP 3/4: COPY . .
--> 59afb5f7a20
STEP 4/4: RUN export OPENSHIFT_BUILD_REFERENCE=$(git rev-parse FETCH_HEAD) &&     export FETCH_HEAD_CONTENT="$(cat ./.git/FETCH_HEAD)" &&     export OPENSHIFT_BUILD_SOURCE="${FETCH_HEAD_CONTENT##* }" &&     echo "Building ${OPENSHIFT_BUILD_REFERENCE} in ${OPENSHIFT_BUILD_SOURCE}" &&     set -o pipefail &&     cirrus-run --github vrutkovs/okd-os --branch main --show-build-log always | tee /tmp/build.log &&     IMAGE=$(grep "Committing container" -A1 /tmp/build.log | tail -n1 | tr ' ' '\n' | head -n1) &&     sed "s;INITIAL_IMAGE;${IMAGE};g" Dockerfile.template > /tmp/Dockerfile &&     mkdir ./extensions
fatal: ambiguous argument 'FETCH_HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
cat: can't open './.git/FETCH_HEAD': No such file or directory
Building FETCH_HEAD in
Build created: https://cirrus-ci.com/build/6578714799505408
............................................................
............................................................
...
Build failed, see log below:

## Task: cosa

## Task instruction: clone
git clone "" .
fatal: repository '' does not exist

Exit status: 128

**Comment by fortinj66** [comment]
do a `git fetch`

You usually only have to do this once...
