### ISSUE TITLE
why are yum repos disabled?

### ISSUE THREAD

**Issue by cgwalters** [openshift/okd-machine-os#445]
Why did you do https://github.com/openshift/okd-machine-os/pull/432/commits/fa36292ab6710098e01269832fc110f50f1f55ad ?

This breaks the basic experience of layering a custom image.

**Comment by vrutkovs** [comment]
In non-layered installs this could lead to unpredictable results, as MCO would pull in updates from the repos along with machine-os-content.

We probably don't need this anymore indeed

**Comment by cgwalters** [comment]
> In non-layered installs this could lead to unpredictable results, as MCO would pull in updates from the repos along with machine-os-content.

That case no longer exists by default though right?

**Comment by vrutkovs** [comment]
Right, let me make a PR
