### ISSUE TITLE
stop referencing `machine-os-content`

### ISSUE THREAD

**Issue by cgwalters** [openshift/okd-machine-os#457]
AIUI current OKD is using `machine-os-content` as a way to find "the default OS image" - it's making it be a new format image.  

I guess actually we could just do that for OCP/RHCOS too, i.e. do a hard cutover and just ship `rhel-coreos-8` as a retagging.  I'm not opposed to that.  But it feels better to make a "clean cut" and have a new image in the new format, and crucially define a better way to find "the default OS image".  Which *could* just be another new tag...like `default-operating-system` or something.

Anyways the bootstrap phase currently does
```
MACHINE_CONFIG_OSCONTENT=$(image_for machine-os-content)
```

and this will eventually break if we do https://github.com/openshift/machine-config-operator/pull/3364

**Comment by LorbusChris** [comment]
The fix for this is included in https://github.com/openshift/installer/pull/6443, particularly https://github.com/openshift/installer/pull/6443/commits/55bbb1086574f73a92d4cdd6f5051e68e3325396

**Comment by LorbusChris** [comment]
@cgwalters not sure you're aware, we just got this from our latest OKD/SCOS CI release try:
```
operator "driver-toolkit" contained an invalid image-references file: no input image tag named "machine-os-content"
```

**Comment by LorbusChris** [comment]
Ah, that's https://github.com/openshift/driver-toolkit/pull/102
